AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PPandLPricesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: PPandLPrices
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
